### ISSUE TITLE
Gem missing jar dependencies

### ISSUE THREAD

**Issue by darkcamper** [bryanklewis/logstash-output-azure_event_hubs#1]
Hi! After installing this plugin and configuring the pipeline to use it, logstash complains about being unable to load 'proton-j' and other jar dependencies. I've manually downloaded the .gem file and it seems to be missing all vendor dependencies.

I've been able to make the plugin work from the sources, but it'd be nice if you could re-upload the fixed gem so that 'logstash-plugin install' worked.

Thanks a lot, and have a happy new year!

**Comment by bryanklewis** [comment]
@darkcamper Thanks for taking the time to open an issue. Im pretty sure i have this resolved, but ill need to verify later tonight. I pushed it out to ruby gems, let me know if it now works as expected.

**Comment by darkcamper** [comment]
@bryanklewis I've just installed the new version and it seems to work fine!

Thanks a lot!
