### ISSUE TITLE
service_uri param is not working properly

### ISSUE THREAD

**Issue by TheNathanGift** [bryanklewis/logstash-output-azure_event_hubs#2]
I'm looking to send events to an Event Hub in the Azure Gov cloud with a different service uri but am running into an error:

[2020-04-24T12:17:16,376][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<NameError: no method 'setEndpoint' for arguments (org.jruby.RubyString) on Java::ComMicrosoftAzureEventhubs::ConnectionStringBuilder>

Looks like the setEndpoint method is looking for a URI object but the param is being mapped to a string. Is there a specific format that was used to get this working or is this a bug?

**Comment by bryanklewis** [comment]
@TheNathanGift My notifications were not setup correctly, so i didnt see your issue. Sorry about that. Your right, i think the name is misleading and there is a bug in how it configures the endpoint. Looking at the [SDK docs](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.eventhubs.connectionstringbuilder.setendpoint?view=azure-java-legacy), this param should be called domain as the setEndpoint method requires 2 properties of string or a single URI. Ill try and get a fix to you soon.

**Comment by bryanklewis** [comment]
Ok, i think its resolved, but i do not have a national cloud subscription anywhere to test. Let me know if there is still errors.

**Comment by bryanklewis** [comment]
https://github.com/bryanklewis/logstash-output-azure_event_hubs/commit/f53527c1146a481d3ce4011ed052038e6ca41212
