### ISSUE TITLE
sas key problem

### ISSUE THREAD

**Issue by IzekChen** [bryanklewis/logstash-output-azure_event_hubs#3]
I have tried the plugin didn't understand what is the SAS key is.
from the token structure, I can see there are "sr", "sig", "see" and "skn".
I assumed that the sas_key_name is "skn"
but what will be the sas_key?

Is there any example I can refer to?

Now I put something like below:
sas_key => 'sig=XXXXX&se=XXXX'
but with no luck

**Comment by bryanklewis** [comment]
Looks like you figured out your question, but the SAS key can be found from the portal after creating your eventhub. https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string#get-connection-string-from-the-portal

**Comment by IzekChen** [comment]
Than you for the reply.
Yes, I did. I found out that there are different thing.
Would it be possible to support SAS token?
Or we shouldn't use SAS token?

**Comment by bryanklewis** [comment]
No, there is no need as the token is managed by the Azure SDK library. This plugin uses the Java azure-eventhubs class to create AMQP based connections. What your probably mixing up is the Azure Event Hubs service has an HTTP endpoint that can also be used to send events. HTTP uses a SAS created token in the web api call. AMQP is significantly faster and better performance under heavy load vs HTTP.

**Comment by IzekChen** [comment]
Thank you for the clarification. Very useful information
