### ISSUE TITLE
Encryption in transit

### ISSUE THREAD

**Issue by nikuljain** [bryanklewis/logstash-output-azure_event_hubs#4]
Is it possible to add a cert parameter or a way to ensure encryption in transit

**Comment by bryanklewis** [comment]
EventHubs operates on TLS always, but if you wanted to ensure, you would have to encrypt the payload before sending. I think this is possible, but would add delay to outputing the data and the queue could fall behind. In my opinion, if the data is that sensitive i would address this with network settings such as vpn/vnets to Microsoft's Azure cloud and not delay the ingest with encrypt/decrypt processing at the data level.
