### ISSUE TITLE
Can you specify a consumer_group?

### ISSUE THREAD

**Issue by CFStephenHale** [bryanklewis/logstash-output-azure_event_hubs#5]
Sorry if I missed it but I can't find where you can specify a consumer_group if you don't wish to use $Default. Thank you.

**Comment by bryanklewis** [comment]
Good on you for thinking about consumer_groups in your solution, however in this case this plugin only _writes_ to an Azure Event Hub. Consumer Groups are for when you are _reading_ off the event hub. So each downstream app from your event hub would have its own consumer group. See the [explanation/diagram here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#event-consumers). When your writing to an event hub, the architecture of the service is such that a 'producer or writer group' is irrelevant.

**Comment by CFStephenHale** [comment]
Sorry for my ignorance. Thank you for the education. :) Appreciate the quick response.
