### ISSUE TITLE
Logstash onConnectionError 

### ISSUE THREAD

**Issue by adsalun** [bryanklewis/logstash-output-azure_event_hubs#8]
Hey @bryanklewis 
following is the Warning I am receiving at the logstash end where I have enabled this plugin:
to continue the log flow I have to restart the service. Is there any possible way to automate the continuous flow and avoid this error?

[WARN ][com.microsoft.azure.eventhubs.impl.MessagingFactory][###] onConnectionError messagingFactory[MF_ef3613_1638427488081], hostname[###], error[The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId : ###, SystemTracker:gateway5, Timestamp:2021-12-07T03:20:55]

**Comment by bryanklewis** [comment]
This is a common message coming from Azure Java SDK. It is generally benign should just be ignored.

**Comment by adsalun** [comment]
is there any workaround for continuity for sending logs?

**Comment by bryanklewis** [comment]
i filter them out at either the filebeat or logstash level
