### ISSUE TITLE
received event properties on undefined (after setting via properties_bag)

### ISSUE THREAD

**Issue by ebegue** [bryanklewis/logstash-output-azure_event_hubs#9]
Hey thanks for this gem!

I've been developing with it fine and dandy, but when I tried to add properties via properties_bag, I get undefined. 

My process is logstash -> eventhub -> function app consumes.

To make things clean, I'm ignoring my function app for now and just made an ultra simple new node project locally to subscribe to the events from the following guide:

[link ](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-node-get-started-send)`https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-node-get-started-send`

which after being configured, successfully receives events from logstash, but the `properties` field per a debug is undefined

Here's my output binding in logstash, as per your example:

`azure_event_hubs {
   service_namespace => "EVENTHUBNAMESPACE"
    event_hub => "EVENTHUBVALUE"
    sas_key_name => "RootManageSharedAccessKey"
   sas_key => "SASKEYVALUE"
    properties_bag => {"Table" => "rv_health" "Format" => "JSON" "IngestionMappingReference" => "rv_health_mapping"}
 }`

but again, the event's I receive look like:
```
{
  "body": {
    "pipeline_version": "1",
    "pipeline_host": "0924febe44aa",
    "source": "RV18_VGS",
    "pipeline_path": "/usr/share/logstash/input/rg_health/rv_health_small.log",
    "pipeline_ingest_timestamp": "2022-03-02T15:36:34.535Z",
    "ts": "20200312T194132.819207Z",
    "success": true,
    "data": {
      "test": "testVal"
    },
    "elapsed": 0.006981
  },
  "offset": "4295524656",
  "sequenceNumber": 1262,
  "enqueuedTimeUtc": "2022-03-02T15:36:35.322Z",
  "systemProperties": {}
}
```

Any suggestions? Am I doing something silly?

Thanks!

**Comment by ebegue** [comment]
nope - not your problem!

**Comment by bryanklewis** [comment]
sounds like you figured out whatever the config was that you needed.
